# syntax=docker/dockerfile:1

FROM golang:1.19.5 AS build

WORKDIR /app

COPY go.mod go.sum ./
COPY inceptor ./inceptor
COPY playtonic ./playtonic
COPY cmd ./cmd

RUN go build -o /playtonic ./cmd/playtonic/main.go

FROM ubuntu:22.04

WORKDIR /

COPY --from=build /playtonic /

EXPOSE 8080

CMD [ "/playtonic" ]
