# syntax=docker/dockerfile:1

FROM golang:1.19.5 AS build

WORKDIR /app

COPY go.mod go.sum ./
COPY inceptor ./inceptor
COPY playtonic ./playtonic
COPY cmd ./cmd

RUN go build -o /inceptor ./cmd/inceptor/main.go

FROM ubuntu:22.04

WORKDIR /

COPY --from=build /inceptor /

EXPOSE 8080

CMD [ "/inceptor" ]
